apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  namespace: default
  labels:
    component: elk
    role: kibana
spec:
  replicas: 1
  selector:
    component: elk
    role: kibana
  template:
    metadata:
      labels:
        component: elk
        role: kibana
    spec:

      containers:
        - name: kibana
          image: shajalahamed/docker-kibana
          env:
            - name: KIBANA_ES_URL
              value: "http://elasticsearch.default.svc.cluster.local:9200"
            - name: KUBERNETES_TRUST_CERT
              value: "true"
          ports:
            - containerPort: 5601
              name: http
              protocol: TCP